App\Dto\ImageDto:
    attributes:
        id:
            groups: [ 'image:get' ]
        filePath:
            groups: [ 'image:get', 'club:item:get', 'gameType:item:get' ]
        width:
            groups: [ 'image:get', 'club:item:get', 'gameType:item:get' ]
        height:
            groups: [ 'image:get', 'club:item:get', 'gameType:item:get' ]
