App\Dto\MatchGameDto:
    attributes:
        id:
            groups: [ 'matchGame:collection:get', 'matchGame:item:get' ]
        homeTeam:
            groups: [ 'matchGame:collection:get', 'matchGame:item:get' ]
        awayTeam:
            groups: [ 'matchGame:collection:get', 'matchGame:item:get' ]
        dateTime:
            groups: [ 'matchGame:collection:get', 'matchGame:item:get' ]
        gameType:
            groups: [ 'matchGame:collection:get', 'matchGame:item:get' ]
        season:
            groups: [ 'matchGame:item:get' ]
        round:
            groups: [ 'matchGame:item:get' ]
        venue:
            groups: [ 'matchGame:item:get' ]
        referee:
            groups: [ 'matchGame:item:get' ]
        firstAssistantReferee:
            groups: [ 'matchGame:item:get' ]
        isFirstAssistantNonProfitable:
            groups: [ 'matchGame:item:get' ]
        secondAssistantReferee:
            groups: [ 'matchGame:item:get' ]
        isSecondAssistantNonProfitable:
            groups: [ 'matchGame:item:get' ]
        fourthOfficial:
            groups: [ 'matchGame:item:get' ]
        refereeObserver:
            groups: [ 'matchGame:item:get' ]
        delegate:
            groups: [ 'matchGame:item:get' ]
        moreInfo:
            groups: [ 'matchGame:item:get' ]
