resources:
    App\Dto\ClubDto:
        properties:
            id:
                identifier: true
            name:
                writable: true
            emblem:
                writable: true
        shortName: 'club'
        collectionOperations:
            get:
                method: GET
                path: /clubs.{_format}
                normalization_context:
                    groups: [ 'club:collection:get' ]
            post:
                methods: POST
                path: /clubs
            teams:
                method: GET
                path: /clubs/{id}/teams.{_format}
                controller: App\Controller\Api\ClubTeams
                normalization_context:
                    groups: [ 'single:club:team:collection:get' ]
        itemOperations:
            get:
                method: GET
                path: /clubs/{id}
                normalization_context:
                    groups: [ 'club:item:get' ]
        attributes:
            denormalization_context:
                groups: [ 'club:write' ]
                api_allow_update: true
