resources:
    App\Dto\ClubDto:
        properties:
            id:
                identifier: true
            name:
                writable: true
            emblem:
                writable: true
        shortName: 'club'
        collectionOperations:
            get:
                method: GET
                path: /clubs.{_format}
                normalization_context:
                    groups: [ 'club:collection:get' ]
            post:
                method: POST
            teams:
                method: GET
                path: /club/{id}/teams.{_format}
                controller: App\Controller\Api\ClubTeams
                normalization_context:
                    groups: [ 'single:club:team:collection:get' ]
        itemOperations:
            get:
                method: GET
                path: /club/{id}
                normalization_context:
                    groups: [ 'club:item:get' ]
            put:
                method: PUT
                path: /club/{id}
            delete:
                method: DELETE
                path: /club/{id}
        attributes:
            denormalization_context:
                groups: [ 'club:write' ]
