resources:
    App\Dto\PersonDto:
        properties:
            id:
                identifier: true
            firstName:
                writable: true
            lastName:
                writable: true
            mobilePhone:
                writable: true
            isDelegate:
                writable: true
            isReferee:
                writable: true
            isRefereeObserver:
                writable: true
        shortName: 'person'
        collectionOperations:
            get:
                method: GET
                path: /people.{_format}
                normalization_context:
                    groups: [ 'person:collection:get' ]
            post:
                method: POST
            delegates:
                method: GET
                path: /people/delegates.{_format}
                controller: App\Controller\Api\People\Delegates
                normalization_context:
                    groups: [ 'person:delegate:collection:get' ]
            referees:
                method: GET
                path: /people/referees.{_format}
                controller: App\Controller\Api\People\Referees
                normalization_context:
                    groups: [ 'person:referee:collection:get' ]
            refereeObservers:
                method: GET
                path: /people/referee-observers.{_format}
                controller: App\Controller\Api\People\RefereeObservers
                normalization_context:
                    groups: [ 'person:refereeObserver:collection:get' ]
        itemOperations:
            get:
                method: GET
                path: /person/{id}
                normalization_context:
                    groups: [ 'person:item:get' ]
        attributes:
            denormalization_context:
                groups: [ 'person:write' ]
