resources:
    App\Dto\UserDto:
        properties:
            id:
                identifier: true
            username:
                writable: true
            plainPassword:
                writable: true
        shortName: 'user'
        collectionOperations:
            get:
                method: GET
                path: /users.{_format}
                normalization_context:
                    groups: [ 'user:collection:get' ]
            post:
                method: POST
                path: /users
        itemOperations:
            get:
                method: GET
                path: /users/{id}
                normalization_context:
                    groups: [ 'user:item:get' ]
        attributes:
            denormalization_context:
                groups: [ 'user:write' ]
                api_allow_update: true
