api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Dto'
            - '%kernel.project_dir%/config/mg_api'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        html:   ['text/html']
        jsonld: ['application/ld+json']
