doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: true
        dql:
            datetime_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

imports:
    - { resource: '../../src/Club/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/GameType/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/Image/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/MatchGame/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/Person/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/Shared/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/Team/Symfony/Resources/config/packages/doctrine.yaml' }
    - { resource: '../../src/User/Symfony/Resources/config/packages/doctrine.yaml' }
