doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            ClubId: App\Dbal\Types\ClubIdType
            GameTypeId: App\Dbal\Types\GameTypeIdType
            ImageId: App\Dbal\Types\ImageIdType
            MatchGameBillId: App\Dbal\Types\MatchGameBillIdType
            MatchGameId: App\Dbal\Types\MatchGameIdType
            PersonId: App\Dbal\Types\PersonIdType
            TeamId: App\Dbal\Types\TeamIdType
            UserId: App\Dbal\Types\UserIdType
            UserRoleId: App\Dbal\Types\UserRoleIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/DoctrineMapping'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
