security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: Sudoku648\Meczyki\User\Domain\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - Sudoku648\Meczyki\Security\Infrastructure\MatchGamesAuthenticator
            logout:
                path: app_logout
            user_checker: Sudoku648\Meczyki\Security\Infrastructure\UserChecker
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            switch_user: { role: ROLE_SUPER_ADMIN }

    access_control:


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
