clubs_front:
    controller: App\Controller\Club\ClubFrontController::front
    path: /kluby
    methods: [ GET ]

club_single:
    controller: App\Controller\Club\ClubSingleController
    path: /klub/{club_id}
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]

club_create:
    controller: App\Controller\Club\ClubCreateController
    path: /klub/nowy
    methods: [ GET, POST ]

club_edit:
    controller: App\Controller\Club\ClubEditController
    path: /klub/{club_id}/edytuj
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

club_delete:
    controller: App\Controller\Club\ClubDeleteController::delete
    path: /klub/{club_id}/usun
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]

club_delete_batch:
    controller: App\Controller\Club\ClubDeleteController::deleteBatch
    path: /kluby/usun
    methods: [ POST ]

club_emblem_delete:
    controller: App\Controller\Club\ClubDeleteEmblemController
    path: /klub/{club_id}/usun-herb
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]
