delegates_list:
    controller: App\Controller\Person\Delegate\DelegateListController::list
    path: /osoby/delegaci
    methods: [ GET ]

delegate_fetch:
    controller: App\Controller\Person\Delegate\DelegateListController::fetch
    path: /people/delegates/fetch
    methods: [ POST ]

delegate_create:
    controller: App\Controller\Person\Delegate\DelegateCreateController
    path: /osoby/delegat/nowy
    methods: [ GET, POST ]
