game_types_front:
    controller: App\Controller\GameType\GameTypeFrontController::front
    path: /typy-rozgrywek
    methods: [ GET ]

game_type_single:
    controller: App\Controller\GameType\GameTypeSingleController
    path: /typ-rozgrywek/{game_type_id<\d+>}
    methods: [ GET ]

game_type_create:
    controller: App\Controller\GameType\GameTypeCreateController
    path: /typ-rozgrywek/nowy
    methods: [ GET, POST ]

game_type_edit:
    controller: App\Controller\GameType\GameTypeEditController
    path: /typ-rozgrywek/{game_type_id<\d+>}/edytuj
    methods: [ GET, POST ]

game_type_delete:
    controller: App\Controller\GameType\GameTypeDeleteController::delete
    path: /typ-rozgrywek/{game_type_id<\d+>}/usun
    methods: [ POST ]

game_type_delete_batch:
    controller: App\Controller\GameType\GameTypeDeleteController::deleteBatch
    path: /typy-rozgrywek/usun
    methods: [ POST ]

game_type_image_delete:
    controller: App\Controller\GameType\GameTypeDeleteImageController
    path: /typ-rozgrywek/{game_type_id<\d+>}/usun-obrazek
    methods: [ POST ]
