match_game_bill_single:
    controller: App\Controller\MatchGameBill\MatchGameBillSingleController
    path: /mecz/{match_game_id}/rachunek/{match_game_bill_id}
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        match_game_bill_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]

match_game_bill_create:
    controller: App\Controller\MatchGameBill\MatchGameBillCreateController
    path: /mecz/{match_game_id}/rachunek/nowy
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

match_game_bill_edit:
    controller: App\Controller\MatchGameBill\MatchGameBillEditController
    path: /mecz/{match_game_id}/rachunek/{match_game_bill_id}/edytuj
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        match_game_bill_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

match_game_bill_delete:
    controller: App\Controller\MatchGameBill\MatchGameBillDeleteController::delete
    path: /mecz/{match_game_id}/rachunek/{match_game_bill_id}/usun
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        match_game_bill_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]

match_game_bill_download:
    controller: App\Controller\MatchGameBill\MatchGameBillDownloadController
    path: /mecz/{match_game_id}/rachunek/{match_game_bill_id}/pobierz
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        match_game_bill_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-6[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]
