match_games_front:
    controller: App\Controller\MatchGame\MatchGameFrontController::front
    path: /mecze
    methods: [ GET ]

match_game_fetch:
    controller: App\Controller\MatchGame\MatchGameFrontController::fetch
    path: /match_games/fetch
    methods: [ POST ]

match_game_single:
    controller: App\Controller\MatchGame\MatchGameSingleController
    path: /mecz/{match_game_id}
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]

match_game_create:
    controller: App\Controller\MatchGame\MatchGameCreateController
    path: /mecz/nowy
    methods: [ GET, POST ]

match_game_edit:
    controller: App\Controller\MatchGame\MatchGameEditController
    path: /mecz/{match_game_id}/edytuj
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

match_game_delete:
    controller: App\Controller\MatchGame\MatchGameDeleteController::delete
    path: /mecz/{match_game_id}/usun
    requirements:
        match_game_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]

match_game_delete_batch:
    controller: App\Controller\MatchGame\MatchGameDeleteController::deleteBatch
    path: /mecze/usun
    methods: [ POST ]
