people_list:
    controller: App\Controller\Person\PersonListController::list
    path: /osoby
    methods: [ GET ]

person_fetch:
    controller: App\Controller\Person\PersonListController::fetch
    path: /people/fetch
    methods: [ POST ]

person_single:
    controller: App\Controller\Person\PersonSingleController
    path: /osoba/{person_id}
    requirements:
        person_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]

person_create:
    controller: App\Controller\Person\PersonCreateController
    path: /osoba/nowa
    methods: [ GET, POST ]

person_edit:
    controller: App\Controller\Person\PersonEditController
    path: /osoba/{person_id}/edytuj
    requirements:
        person_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

person_delete:
    controller: App\Controller\Person\PersonDeleteController::delete
    path: /osoba/{person_id}/usun
    requirements:
        person_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]

person_delete_batch:
    controller: App\Controller\Person\PersonDeleteController::deleteBatch
    path: /osoby/usun
    methods: [ POST ]

person_personal_info_edit:
    controller: App\Controller\Person\PersonPersonalInfoEditController
    path: /dane-osobowe
    methods: [ GET, POST ]
