referee_observers_list:
    controller: App\Controller\Person\RefereeObserver\RefereeObserverListController::list
    path: /osoby/obserwatorzy
    methods: [ GET ]

referee_observer_fetch:
    controller: App\Controller\Person\RefereeObserver\RefereeObserverListController::fetch
    path: /people/referee_observers/fetch
    methods: [ POST ]

referee_observer_create:
    controller: App\Controller\Person\RefereeObserver\RefereeObserverCreateController
    path: /osoby/obserwator/nowy
    methods: [ GET, POST ]
