referees_list:
    controller: App\Controller\Person\Referee\RefereeListController::list
    path: /osoby/sedziowie
    methods: [ GET ]

referee_fetch:
    controller: App\Controller\Person\Referee\RefereeListController::fetch
    path: /people/referees/fetch
    methods: [ POST ]

referee_create:
    controller: App\Controller\Person\Referee\RefereeCreateController
    path: /osoby/sedzia/nowy
    methods: [ GET, POST ]
