teams_list:
    controller: App\Controller\Team\TeamListController::list
    path: /kluby/druzyny
    methods: [ GET ]

team_fetch:
    controller: App\Controller\Team\TeamListController::fetch
    path: /clubs/teams/fetch
    methods: [ POST ]

team_single:
    controller: App\Controller\Team\TeamSingleController
    path: /klub/{club_id}/druzyna/{team_id}
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        team_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET ]

team_create:
    controller: App\Controller\Team\TeamCreateController
    path: /klub/{club_id}/druzyna/nowa
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

team_edit:
    controller: App\Controller\Team\TeamEditController
    path: /klub/{club_id}/druzyna/{team_id}/edytuj
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        team_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ GET, POST ]

team_delete:
    controller: App\Controller\Team\TeamDeleteController::delete
    path: /klub/{club_id}/druzyna/{team_id}/usun
    requirements:
        club_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
        team_id: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[6-7][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
    methods: [ POST ]

team_delete_batch:
    controller: App\Controller\Team\TeamDeleteController::deleteBatch
    path: /kluby/druzyny/usun
    methods: [ POST ]
