club:
    resource: '../src/Club/Symfony/Resources/config/routes.php'
dashboard:
    resource: '../src/Dashboard/Symfony/Resources/config/routes.php'
game_type:
    resource: '../src/GameType/Symfony/Resources/config/routes.php'
match_game:
    resource: '../src/MatchGame/Symfony/Resources/config/routes.php'
person:
    resource: '../src/Person/Symfony/Resources/config/routes.php'
security:
    resource: '../src/Security/Symfony/Resources/config/routes.php'
team:
    resource: '../src/Team/Symfony/Resources/config/routes.php'
user:
    resource: '../src/User/Symfony/Resources/config/routes.php'
